services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    container_name: examMySQLDatabase
    environment:
      MYSQL_ROOT_PASSWORD: _root@123
      MYSQL_DATABASE: examDB
      MYSQL_USER: exam
      MYSQL_PASSWORD: exam@123
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8081:80
    container_name: phpmyadminExam
